### ISSUE TITLE
Need support for overflow based style wrt to X and Y axis

### ISSUE THREAD

**Issue by SyedUmerHasan** [numldesign/numl#206]
# 🚀 Feature request

> Support for X and Y-axis in the overflow styles

## 🧱 Problem Statement / Justification

> Currently, NUML doesn't seem to have any support for overflow on the X and Y axis only, so we need to add its support in https://github.com/numldesign/numl/blob/main/src/styles/overflow.js

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API
```jsx
<nu-block overflow="x-axis">
This is where my componnet exist
</nu-block>
<nu-block overflow="y-axis">
This is where my componnet exist
</nu-block>
```

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

**Comment by tenphi** [comment]
It has. Like in original overflow CSS property:
"The overflow property is specified as one or two keywords chosen from the list of values below. If two keywords are specified, the first applies to overflow-x and the second to overflow-y. Otherwise, both overflow-x and overflow-y are set to the same value."
